apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: lastone
  name: lastone
spec:
  containers:
  - args:
    - sleep
    - "3600"
    image: busybox
    name: lastone
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
