apiVersion: v1
kind: Namespace
metadata:
  name: restricted
  labels:
    name: restricted

---
apiVersion: v1
kind: Pod
metadata:
  name: lab8server
  namespace: restricted
  labels:
    app: lab8server
spec:
  containers:
    - name: lab8server
      image: nginx

---
apiVersion: v1
kind: Pod
metadata:
  name: Sleepybox1
  namespace: default
  labels:
    app: sleepy
spec:
  containers:
    - name: Sleepybox1
      image: busybox
      command:
        - sleep
        - "3600"

---
apiVersion: v1
kind: Pod
metadata:
  name: Sleepybox2
  namespace: default
  labels:
    sleepybox: "2"
spec:
  containers:
    - name: Sleepybox2
      image: busybox
      command:
        - sleep
        - "3600"
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: restricted
  name: restricted-access
spec:
  podSelector:
    matchLabels: { }
  ingress:
    - from:
        - podSelector:
            matchLabels:
              sleepybox: "2"
